export const mockFighter = {
  id: 1,
  firstName: 'Islam',
  lastName: 'Makhachev',
  nickname: null,
  height: 178,
  weight: 70,
  reach: 178,
  stance: 'Southpaw',
  dateOfBirth: new Date('1991-10-27'),
  wins: 26,
  losses: 1,
  draws: 0,
  winsByKo: 4,
  winsBySub: 11,
  winsByDec: 11,
  strikingAccuracy: 59,
  takedownAccuracy: 61,
  strikingDefense: 62,
  takedownDefense: 90,
  picture: null,
};

export const mockFightersList = [
  mockFighter,
  {
    ...mockFighter,
    id: 2,
    firstName: 'Alexander',
    lastName: 'Volkanovski',
    nickname: 'The Great',
    height: 168,
    weight: 66,
    reach: 182,
    stance: 'Orthodox',
    dateOfBirth: new Date('1988-09-29'),
    wins: 26,
    losses: 4,
    draws: 0,
    winsByKo: 13,
    winsBySub: 3,
    winsByDec: 10,
    strikingAccuracy: 56,
    takedownAccuracy: 36,
    strikingDefense: 58,
    takedownDefense: 73,
  },
  {
    ...mockFighter,
    id: 3,
    firstName: 'Jon',
    lastName: 'Jones',
    nickname: 'Bones',
    height: 193,
    weight: 111,
    reach: 215,
    stance: 'Orthodox',
    dateOfBirth: new Date('1987-07-19'),
    wins: 27,
    losses: 1,
    draws: 0,
    winsByKo: 10,
    winsBySub: 7,
    winsByDec: 10,
    strikingAccuracy: 57,
    takedownAccuracy: 44,
    strikingDefense: 64,
    takedownDefense: 97,
  },
];
